export type Locale = "en" | "am";

export const strings = {
  en: {
    title: "AgriClimate AI Agent",
    subtitle: "Simple, practical guidance for Ethiopian farmers",
    chat: "Chat",
    dashboard: "Dashboard",
    location: "Location (for weather)",
    locationPh: "e.g. Hawassa, SNNPR",
    messagePh: "Ask about rains, crops, pests, soil…",
    send: "Send",
    streaming: "Streaming…",
    thinking: "Thinking…",
    offline:
      "You are offline. Cached advice may be shown; sending needs a connection.",
    attach: "Leaf photo (optional)",
    drop: "Drag & drop or click — preview before send",
    remove: "Remove",
    analyze: "Analyze leaf photo",
    analyzing: "Analyzing…",
    voice: "Voice input (coming soon)",
    voiceHint: "Microphone capture will be added in a future release.",
    newChat: "New chat",
    recent: "Recent advice",
    refresh: "Refresh",
    noAdvice: "No advice yet — start on Chat.",
    problem: "Problem",
    insight: "Insight",
    steps: "Action steps",
    en: "English",
    am: "አማርኛ",
    language: "Language",
    dashboardNote: "Latest assistant replies stored in PostgreSQL.",
  },
  am: {
    title: "AgriClimate AI ወኪል",
    subtitle: "ለኢትዮጵያ ገበሬዎች ቀላል እና ምክር",
    chat: "ውይይት",
    dashboard: "ዳሽቦርድ",
    location: "አካባቢ (ለአየር ንብረት)",
    locationPh: "ለምሳሌ ሀዋሳ",
    messagePh: "ስለ ዝናብ፣ ሰብል፣ ተባይ… ይጠይቁ",
    send: "ላክ",
    streaming: "በመፍጠን ላይ…",
    thinking: "በማሰብ ላይ…",
    offline: "ከመስመር ውጭ ነዎት። የተቀመጠ ምክር ሊታይ ይችላል።",
    attach: "የቅጠል ፎቶ (አማራጭ)",
    drop: "ጎትት እና ጣል ወይም ጠቅ ያድርጉ",
    remove: "አስወግድ",
    analyze: "ቅጠል ተንተን",
    analyzing: "በመተንተን ላይ…",
    voice: "የድምጽ ግቤት (በቅርቡ)",
    voiceHint: "የማይክሮፎን መቆጣጠሪያ በሚቀጥለው ስሪት ይመጣል።",
    newChat: "አዲስ ውይይት",
    recent: "የቅርብ ምክር",
    refresh: "አድስ",
    noAdvice: "እስካሁን ምክር የለም።",
    problem: "ችግር",
    insight: "መረዳት",
    steps: "የሥራ እርምጃዎች",
    en: "English",
    am: "አማርኛ",
    language: "ቋንቋ",
    dashboardNote: "የቅርብ ምላሾች በ PostgreSQL ይቆያሉ።",
  },
} as const;

export type Messages = (typeof strings)["en"];
